CREATE TABLE faculties(
	ID INT PRIMARY KEY,
	Name TEXT NOT NULL
);

CREATE TABLE groups(
	ID INT PRIMARY KEY,
	Group_number TEXT NOT NULL,
	Faculty_ID INT REFERENCES faculties(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE students(
	ID INT PRIMARY KEY,
	Fio_student TEXT NOT NULL,
	Account_book INT NOT NULL,
	Group_ID INT REFERENCES groups(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE teachers(
	ID INT PRIMARY KEY,
	Fio_teachers TEXT NOT NULL
);

CREATE TABLE disciplines(
	ID INT PRIMARY KEY,
	Name_discipline TEXT NOT NULL,
	Teacher_ID INT REFERENCES teachers(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE exams(
	ID INT PRIMARY KEY,
	Student_ID INT REFERENCES students(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	Discipline_ID INT REFERENCES disciplines(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	Assessment INT NOT NULL,
	Exam_date DATE NOT NULL
);
